function [ physical_s ] = Physical_Group_Freq( mono_peptide_freq_s )
%--------------------------------------------------------------------------

%Frequencies of physical property groups (5 groups)
%1-Nonpolar & hydrophilic:[GAVLIP]
%2-Polar & noncharged:[FWY]
%3-Polar & charged:[STCMNQ]
%4-Negative charge:[DE]
%5-Positive charge:[RKH]

number_of_proteins = size(mono_peptide_freq_s,1);

physical_s = zeros(number_of_proteins,5);

for i=1:number_of_proteins
    
    physical_s(i,1) = mono_peptide_freq_s(i,AAtoCode('G'))+...
                      mono_peptide_freq_s(i,AAtoCode('A'))+...
                      mono_peptide_freq_s(i,AAtoCode('V'))+...
                      mono_peptide_freq_s(i,AAtoCode('L'))+...
                      mono_peptide_freq_s(i,AAtoCode('I'))+...
                      mono_peptide_freq_s(i,AAtoCode('P'));
                       
    physical_s(i,2) = mono_peptide_freq_s(i,AAtoCode('F'))+...
                      mono_peptide_freq_s(i,AAtoCode('W'))+...
                      mono_peptide_freq_s(i,AAtoCode('Y'));
                       
    physical_s(i,3) = mono_peptide_freq_s(i,AAtoCode('S'))+...
                      mono_peptide_freq_s(i,AAtoCode('T'))+...
                      mono_peptide_freq_s(i,AAtoCode('C'))+...
                      mono_peptide_freq_s(i,AAtoCode('M'))+...
                      mono_peptide_freq_s(i,AAtoCode('N'))+...
                      mono_peptide_freq_s(i,AAtoCode('Q'));
                           
    physical_s(i,4) = mono_peptide_freq_s(i,AAtoCode('D'))+...
                      mono_peptide_freq_s(i,AAtoCode('E'));
                           
    physical_s(i,5) = mono_peptide_freq_s(i,AAtoCode('R'))+...
                      mono_peptide_freq_s(i,AAtoCode('K'))+...
                      mono_peptide_freq_s(i,AAtoCode('H'));
end

%--------------------------------------------------------------------------
end

